"""empty message

Revision ID: 563bf5c936de
Revises: 017d354c022f
Create Date: 2019-06-18 20:12:47.253291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563bf5c936de'
down_revision = '017d354c022f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['account_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['account_users.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.add_column('orders', sa.Column('order_total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'order_total')
    op.drop_table('order_items')
    # ### end Alembic commands ###
