"""Add deleted field to role table

Revision ID: 9721ecb7b49c
Revises: ea00fd241621
Create Date: 2023-05-08 10:54:43.490052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9721ecb7b49c'
down_revision = 'ea00fd241621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
