"""Add deleted field to user table

Revision ID: bab7f466f61d
Revises: fca5a6c4797a
Create Date: 2023-05-07 13:43:18.337276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab7f466f61d'
down_revision = 'fca5a6c4797a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
